#!/bin/bash
# git-autosave.sh - local-only git safety net (NO GitHub, NO push).
# A "time machine" for work folders so nothing is ever lost - the user never has
# to run a git command. Git identity is taken from the user's own global git
# config; this script never sets a name or email.
#
# Modes:
#   ensure  - SessionStart / setup: if CWD isn't a git repo, `git init` + write a
#             safe .gitignore. If it IS a repo but has no .gitignore, write one
#             (so the first commit can't leak secrets).
#   commit  - checkpoint: stage everything + commit LOCALLY. Only if there are changes.
#
# Hard guarantees:
#   - NEVER pushes anywhere. Local commits only.
#   - Only ever operates inside ~/Documents/  (never random dirs). Adjust the
#     guard below to your own work root if you keep projects elsewhere.
#   - Never overwrites an existing .gitignore.
#   - Skips headless (claude -p) sessions.
set -uo pipefail

MODE="${1:-}"
CWD="$(pwd)"

# Skip headless (claude -p) subprocess sessions.
PARENT_CMD=$(ps -o args= -p "$PPID" 2>/dev/null || echo "")
if [[ "$PARENT_CMD" == *" -p "* ]] || [[ "$PARENT_CMD" == *" -p" ]]; then exit 0; fi

# Only operate inside the user's work folder. Change this guard if your projects
# live somewhere other than ~/Documents.
case "$CWD" in
  "$HOME"/Documents/*) : ;;
  *) exit 0 ;;
esac

write_gitignore_if_missing() {
  [[ -f "$CWD/.gitignore" ]] && return 0
  # Prefer the universal standard template (single source of truth). Fall back to
  # the inline minimal secrets-first version if the template is missing.
  local tpl="$HOME/.claude/templates/gitignore"
  if [[ -f "$tpl" ]]; then
    cp "$tpl" "$CWD/.gitignore"
    return 0
  fi
  cat > "$CWD/.gitignore" <<'EOF'
# Auto-generated by git-autosave (local safety net). Edit freely.
# --- Secrets - never version these ---
.env
.env.*
*.env
**/.env
**/.env.*
!.env.example
!.env.template
!**/.env.example
!**/.env.template
*.key
*.pem
*.p12
*.pfx
*-credentials.json
credentials.json
.credentials.json
**/secrets/*.env
*.dec.yaml
# --- Dependencies / build output ---
**/node_modules/
**/.next/
**/dist/
**/build/
**/.venv/
**/__pycache__/
# --- OS / editor noise ---
.DS_Store
Thumbs.db
*.swp
*.swo
EOF
}

is_git() { git -C "$CWD" rev-parse --is-inside-work-tree >/dev/null 2>&1; }

case "$MODE" in
  ensure)
    if ! is_git; then
      git -C "$CWD" init -q || exit 0
      # Git identity is intentionally NOT set here - it uses the user's own
      # global ~/.gitconfig (user.name / user.email).
    fi
    write_gitignore_if_missing
    ;;
  commit)
    is_git || exit 0
    git -C "$CWD" add -A 2>/dev/null || exit 0
    # Nothing staged -> nothing to do.
    git -C "$CWD" diff --cached --quiet 2>/dev/null && exit 0
    TS=$(date "+%Y-%m-%d %H:%M")
    git -C "$CWD" commit -q -m "checkpoint: auto-save $TS" 2>/dev/null || true
    ;;
  *)
    echo "usage: git-autosave.sh {ensure|commit}" >&2
    exit 1
    ;;
esac
exit 0
