#!/bin/bash
# git-autosave.sh - gives a work folder a local git history (NO GitHub, NO push), so nothing is lost
# and the user never has to run a git command. Git identity comes from the user's own global git
# config; this script never sets a name or email.
#
# Usage: git-autosave.sh ensure
#   If the current folder isn't a git repository: `git init` + write a safe .gitignore. If it is one
#   but has no .gitignore, write one (so the first commit can't leak secrets).
#
# Hard guarantees:
#   - NEVER pushes anywhere, never commits.
#   - Only ever operates inside the workspace folder (see below), never in random folders.
#   - Never turns a container root (<workspace>/_APPS, <workspace>/_CLIENTS) into a repository: each
#     project or client inside it gets its own.
#   - Never overwrites an existing .gitignore.
#   - Skips headless (claude -p) sessions where it can tell (macOS and Linux; Git Bash's ps cannot
#     show a process's arguments, so on Windows the check finds nothing and the script runs).
#
# The workspace folder, first match wins:
#   1. $CLAUDE_WORKSPACE_ROOT
#   2. the first line of ~/.claude/workspace-root (the installer writes it when the documents folder is
#      not ~/Documents, for example ~/OneDrive/Documents on Windows); C:\... and /c/... both work
#   3. ~/Documents
# Paths compare case-insensitively on macOS and Windows, whose file systems ignore case.
#
# Runs under bash 3.2 (macOS), GNU bash (Linux) and Git Bash (Windows).
set -uo pipefail

MODE="${1:-}"
CWD="$(pwd)"

# Skip headless (claude -p / --print) sessions. The script runs under the Bash tool's shell, so the
# claude process sits above one or more shells: walk up through the shells to the first process that
# is not one, and skip when that is claude (its executable, or the npm package's cli.js) with -p.
pid="$PPID"
for _ in 1 2 3 4 5 6; do
  [ -n "$pid" ] && [ "$pid" -gt 1 ] 2>/dev/null || break
  args="$(ps -o args= -p "$pid" 2>/dev/null || true)"
  first="${args%% *}"
  first="${first##*/}"
  case "${first#-}" in
    bash|sh|zsh|dash|ksh) pid="$(ps -o ppid= -p "$pid" 2>/dev/null | tr -d ' ')"; continue ;;
  esac
  case "$first $args" in
    claude\ *|claude.exe\ *|*claude-code/cli.js*)
      case " $args " in *" -p "*|*" --print "*) exit 0 ;; esac ;;
  esac
  break
done

workspace_root() {
  local root="${CLAUDE_WORKSPACE_ROOT:-}" drive rest
  if [ -z "$root" ] && [ -f "$HOME/.claude/workspace-root" ]; then
    IFS= read -r root < "$HOME/.claude/workspace-root" || true
  fi
  root="${root%$'\r'}"
  case "$root" in
    [A-Za-z]:|[A-Za-z]:[\\/]*)
      drive="$(printf '%s' "${root:0:1}" | tr '[:upper:]' '[:lower:]')"
      rest="${root:2}"
      root="/$drive${rest//\\//}" ;;
  esac
  case "$root" in
    "~") root="$HOME" ;;
    "~/"*) root="$HOME/${root#\~/}" ;;
  esac
  root="${root%/}"
  printf '%s' "${root:-$HOME/Documents}"
}

# A path as it is compared: lower case where the file system ignores case (macOS, Windows).
comparable() {
  case "${OSTYPE:-}" in
    darwin*|msys*|cygwin*|win*) printf '%s' "$1" | tr '[:upper:]' '[:lower:]' ;;
    *) printf '%s' "$1" ;;
  esac
}

ROOT="$(workspace_root)"
here="$(comparable "$CWD")"
base="$(comparable "$ROOT")"

# Only operate inside the workspace folder.
case "$here" in
  "$base"/*) : ;;
  *) exit 0 ;;
esac

write_gitignore_if_missing() {
  [[ -f "$CWD/.gitignore" ]] && return 0
  # Prefer the universal standard template (single source of truth). Fall back to
  # the inline minimal secrets-first version if the template is missing.
  local tpl="$HOME/.claude/templates/gitignore"
  if [[ -f "$tpl" ]]; then
    cp "$tpl" "$CWD/.gitignore"
    return 0
  fi
  cat > "$CWD/.gitignore" <<'EOF'
# Auto-generated by git-autosave (local safety net). Edit freely.
# --- Secrets - never version these ---
.env
.env.*
*.env
**/.env
**/.env.*
!.env.example
!.env.template
!**/.env.example
!**/.env.template
.envrc
*.key
*.pem
*.p12
*.pfx
*-credentials.json
credentials.json
.credentials.json
**/secrets/*.env
*.dec.yaml
# --- Dependencies / build output ---
**/node_modules/
**/.next/
**/dist/
**/build/
**/.venv/
**/__pycache__/
# --- OS / editor noise ---
.DS_Store
Thumbs.db
desktop.ini
*.swp
*.swo
EOF
}

is_git() { git -C "$CWD" rev-parse --is-inside-work-tree >/dev/null 2>&1; }

# Container roots hold one project (or client) per folder; a repository at the root would
# sweep them all into one history.
NEVER_REPO=""
case "$here" in
  "$base"/_apps|"$base"/_clients|"$base"/_APPS|"$base"/_CLIENTS) NEVER_REPO=1 ;;
esac

case "$MODE" in
  ensure)
    if ! is_git; then
      [[ -n "$NEVER_REPO" ]] && exit 0
      git -C "$CWD" init -q || exit 0
      # Git identity is intentionally NOT set here - it uses the user's own
      # global ~/.gitconfig (user.name / user.email).
    fi
    write_gitignore_if_missing
    ;;
  *)
    echo "usage: git-autosave.sh ensure" >&2
    exit 1
    ;;
esac
exit 0
